[tool.poetry]
name = "IreneAPI"
version = "2.0"
description = "The Websocket and REST API for Irene."
authors = ["MujyKun <mujy@irenebot.com>", "A-Phamfam <alextampham3000@gmail.com>"]
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
]
readme = "README.md"
homepage = "https://api.irenebot.com/"
repository = "https://github.com/MujyKun/IreneAPI"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
quart = "0.16.2"
asyncpg = "0.25.0"
python-dotenv = "0.19.2"
passlib = "1.7.4"
google-api-python-client = "2.12.0"
google-auth = "1.32.1"
google-auth-httplib2 = "0.1.0"
google-auth-oauthlib = "0.4.4"
psycopg2 = "2.9.2"
black = "21.12b0"
pre-commit = "2.16.0"
quart-openapi = {version = "1.7.2", extras = ["doc"]}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"