create or replace function public.addguild(
            t_guildid bigint,
            t_name text,
            t_emojicount integer,
            t_afktimeout integer,
            t_icon text,
            t_ownerid bigint,
            t_banner text,
            t_description text,
            t_mfalevel integer,
            t_splash text,
            t_nitrolevel integer,
            t_boosts integer,
            t_textchannelcount integer,
            t_voicechannelcount integer,
            t_categorycount integer,
            t_emojilimit integer,
            t_membercount integer,
            t_rolecount integer,
            t_shardid integer,
            t_createdate timestamptz,
            t_hasbot bool)
    returns void
    language plpgsql
as
$$
begin
    INSERT INTO public.guilds(guildid,
                              name,
                              emojicount,
                              afktimeout,
                              icon,
                              ownerid,
                              banner,
                              description,
                              mfalevel,
                              splash,
                              nitrolevel,
                              boosts,
                              textchannelcount,
                              voicechannelcount,
                              categorycount,
                              emojilimit,
                              membercount,
                              rolecount,
                              shardid,
                              createdate,
                              hasbot)
    VALUES(t_guildid,
            t_name,
            t_emojicount,
            t_afktimeout,
            t_icon,
            t_ownerid,
            t_banner,
            t_description,
            t_mfalevel,
            t_splash,
            t_nitrolevel,
            t_boosts,
            t_textchannelcount,
            t_voicechannelcount,
            t_categorycount,
            t_emojilimit,
            t_membercount,
            t_rolecount,
            t_shardid,
            t_createdate,
            t_hasbot) ON CONFLICT (guildid) DO NOTHING;
end;
$$;