INSERT INTO groupmembers.bloodtypes(name)
VALUES ('O'), ('A'), ('B'), ('AB') ON CONFLICT DO NOTHING;

INSERT INTO groupmembers.position(name)
VALUES ('Leader'), ('Vocalist'), ('Lead Vocalist'), ('Main Vocalist'), ('Dancer'), ('Main Dancer'), ('Lead Dancer'),
       ('Sub Vocalist'), ('Former'), ('Rapper'), ('Lead Rapper'), ('Main Rapper') ON CONFLICT DO NOTHING;


INSERT INTO blackjack.cardvalues(id, name, value) VALUES
  (1,'Ace of Hearts',11),
  (2,'Two of Hearts',2),
  (3,'Three of Hearts',3),
  (4,'Four of Hearts',4),
  (5,'Five of Hearts',5),
  (6,'Six of Hearts',6),
  (7,'Seven of Hearts',7),
  (8,'Eight of Hearts',8),
  (9,'Nine of Hearts',9),
  (10,'Ten of Hearts',10),
  (11,'Jack of Hearts',10),
  (12,'Queen of Hearts',10),
  (13,'King of Hearts',10),
  (14,'Ace of Diamonds',11),
  (15,'Two of Diamonds',2),
  (16,'Three of Diamonds',3),
  (17,'Four of Diamonds',4),
  (18,'Five of Diamonds',5),
  (19,'Six of Diamonds',6),
  (20,'Seven of Diamonds',7),
  (21,'Eight of Diamonds',8),
  (22,'Nine of Diamonds',9),
  (23,'Ten of Diamonds',10),
  (24,'Jack of Diamonds',10),
  (25,'Queen of Diamonds',10),
  (26,'King of Diamonds',10),
  (27,'Ace of Spades',11),
  (28,'Two of Spades',2),
  (29,'Three of Spades',3),
  (30,'Four of Spades',4),
  (31,'Five of Spades',5),
  (32,'Six of Spades',6),
  (33,'Seven of Spades',7),
  (34,'Eight of Spades',8),
  (35,'Nine of Spades',9),
  (36,'Ten of Spades',10),
  (37,'Jack of Spades',10),
  (38,'Queen of Spades',10),
  (39,'King of Spades',10),
  (40,'Ace of Clubs',11),
  (41,'Two of Clubs',2),
  (42,'Three of Clubs',3),
  (43,'Four of Clubs',4),
  (44,'Five of Clubs',5),
  (45,'Six of Clubs',6),
  (46,'Seven of Clubs',7),
  (47,'Eight of Clubs',8),
  (48,'Nine of Clubs',9),
  (49,'Ten of Clubs',10),
  (50,'Jack of Clubs',10),
  (51,'Queen of Clubs',10),
  (52,'King of Clubs',10) ON CONFLICT DO NOTHING;

INSERT INTO interactions.interactiontypes(name) VALUES ('stepon'), ('stab'), ('choke'), ('pullhair'), ('cuddle'), ('pat'), ('punch'), ('spit'), ('lick'), ('hug'), ('kiss'), ('slap') ON CONFLICT DO NOTHING;


INSERT INTO public.timezones(name, shortname) VALUES ('Europe/Andorra', 'ca'),
                                                     ('Asia/Dubai', 'ar-AE'),
                                                     ('Asia/Kabul', 'fa-AF'),
                                                     ('America/Antigua', 'en-AG'),
                                                     ('America/Anguilla', 'en-AI'),
                                                     ('Europe/Tirane', 'sq'),
                                                     ('Asia/Yerevan', 'hy'),
                                                     ('Africa/Luanda', 'pt-AO'),
                                                     ('America/Argentina/Buenos_Aires', 'es-AR'),
                                                     ('America/Argentina/Cordoba', 'es-AR'),
                                                     ('America/Argentina/Salta', 'es-AR'),
                                                     ('America/Argentina/Jujuy', 'es-AR'),
                                                     ('America/Argentina/Tucuman', 'es-AR'),
                                                     ('America/Argentina/Catamarca', 'es-AR'),
                                                     ('America/Argentina/La_Rioja', 'es-AR'),
                                                     ('America/Argentina/San_Juan', 'es-AR'),
                                                     ('America/Argentina/Mendoza', 'es-AR'),
                                                     ('America/Argentina/San_Luis', 'es-AR'),
                                                     ('America/Argentina/Rio_Gallegos', 'es-AR'),
                                                     ('America/Argentina/Ushuaia', 'es-AR'),
                                                     ('Pacific/Pago_Pago', 'en-AS'),
                                                     ('Europe/Vienna', 'de-AT'),
                                                     ('Australia/Lord_Howe', 'en-AU'),
                                                     ('Antarctica/Macquarie', 'en-AU'),
                                                     ('Australia/Hobart', 'en-AU'),
                                                     ('Australia/Currie', 'en-AU'),
                                                     ('Australia/Melbourne', 'en-AU'),
                                                     ('Australia/Sydney', 'en-AU'),
                                                     ('Australia/Broken_Hill', 'en-AU'),
                                                     ('Australia/Brisbane', 'en-AU'),
                                                     ('Australia/Lindeman', 'en-AU'),
                                                     ('Australia/Adelaide', 'en-AU'),
                                                     ('Australia/Darwin', 'en-AU'),
                                                     ('Australia/Perth', 'en-AU'),
                                                     ('Australia/Eucla', 'en-AU'),
                                                     ('America/Aruba', 'nl-AW'),
                                                     ('Europe/Mariehamn', 'sv-AX'),
                                                     ('Asia/Baku', 'az'),
                                                     ('Europe/Sarajevo', 'bs'),
                                                     ('America/Barbados', 'en-BB'),
                                                     ('Asia/Dhaka', 'bn-BD'),
                                                     ('Europe/Brussels', 'nl-BE'),
                                                     ('Africa/Ouagadougou', 'fr-BF'),
                                                     ('Europe/Sofia', 'bg'),
                                                     ('Asia/Bahrain', 'ar-BH'),
                                                     ('Africa/Bujumbura', 'fr-BI'),
                                                     ('Africa/Porto-Novo', 'fr-BJ'),
                                                     ('America/St_Barthelemy', 'fr'),
                                                     ('Atlantic/Bermuda', 'en-BM'),
                                                     ('Asia/Brunei', 'ms-BN'),
                                                     ('America/La_Paz', 'es-BO'),
                                                     ('America/Kralendijk', 'nl'),
                                                     ('America/Noronha', 'pt-BR'),
                                                     ('America/Belem', 'pt-BR'),
                                                     ('America/Fortaleza', 'pt-BR'),
                                                     ('America/Recife', 'pt-BR'),
                                                     ('America/Araguaina', 'pt-BR'),
                                                     ('America/Maceio', 'pt-BR'),
                                                     ('America/Bahia', 'pt-BR'),
                                                     ('America/Sao_Paulo', 'pt-BR'),
                                                     ('America/Campo_Grande', 'pt-BR'),
                                                     ('America/Cuiaba', 'pt-BR'),
                                                     ('America/Santarem', 'pt-BR'),
                                                     ('America/Porto_Velho', 'pt-BR'),
                                                     ('America/Boa_Vista', 'pt-BR'),
                                                     ('America/Manaus', 'pt-BR'),
                                                     ('America/Eirunepe', 'pt-BR'),
                                                     ('America/Rio_Branco', 'pt-BR'),
                                                     ('America/Nassau', 'en-BS'),
                                                     ('Asia/Thimphu', 'dz'),
                                                     ('Africa/Gaborone', 'en-BW'),
                                                     ('Europe/Minsk', 'be'),
                                                     ('America/Belize', 'en-BZ'),
                                                     ('America/St_Johns', 'en-CA'),
                                                     ('America/Halifax', 'en-CA'),
                                                     ('America/Glace_Bay', 'en-CA'),
                                                     ('America/Moncton', 'en-CA'),
                                                     ('America/Goose_Bay', 'en-CA'),
                                                     ('America/Blanc-Sablon', 'en-CA'),
                                                     ('America/Toronto', 'en-CA'),
                                                     ('America/Nipigon', 'en-CA'),
                                                     ('America/Thunder_Bay', 'en-CA'),
                                                     ('America/Iqaluit', 'en-CA'),
                                                     ('America/Pangnirtung', 'en-CA'),
                                                     ('America/Atikokan', 'en-CA'),
                                                     ('America/Winnipeg', 'en-CA'),
                                                     ('America/Rainy_River', 'en-CA'),
                                                     ('America/Resolute', 'en-CA'),
                                                     ('America/Rankin_Inlet', 'en-CA'),
                                                     ('America/Regina', 'en-CA'),
                                                     ('America/Swift_Current', 'en-CA'),
                                                     ('America/Edmonton', 'en-CA'),
                                                     ('America/Cambridge_Bay', 'en-CA'),
                                                     ('America/Yellowknife', 'en-CA'),
                                                     ('America/Inuvik', 'en-CA'),
                                                     ('America/Creston', 'en-CA'),
                                                     ('America/Dawson_Creek', 'en-CA'),
                                                     ('America/Fort_Nelson', 'en-CA'),
                                                     ('America/Vancouver', 'en-CA'),
                                                     ('America/Whitehorse', 'en-CA'),
                                                     ('America/Dawson', 'en-CA'),
                                                     ('Indian/Cocos', 'ms-CC'),
                                                     ('Africa/Kinshasa', 'fr-CD'),
                                                     ('Africa/Lubumbashi', 'fr-CD'),
                                                     ('Africa/Bangui', 'fr-CF'),
                                                     ('Africa/Brazzaville', 'fr-CG'),
                                                     ('Europe/Zurich', 'de-CH'),
                                                     ('Africa/Abidjan', 'fr-CI'),
                                                     ('Pacific/Rarotonga', 'en-CK'),
                                                     ('America/Santiago', 'es-CL'),
                                                     ('America/Punta_Arenas', 'es-CL'),
                                                     ('Pacific/Easter', 'es-CL'),
                                                     ('Africa/Douala', 'en-CM'),
                                                     ('Asia/Shanghai', 'zh-CN'),
                                                     ('Asia/Urumqi', 'zh-CN'),
                                                     ('America/Bogota', 'es-CO'),
                                                     ('America/Costa_Rica', 'es-CR'),
                                                     ('America/Havana', 'es-CU'),
                                                     ('Atlantic/Cape_Verde', 'pt-CV'),
                                                     ('America/Curacao', 'nl'),
                                                     ('Indian/Christmas', 'en'),
                                                     ('Asia/Nicosia', 'el-CY'),
                                                     ('Asia/Famagusta', 'el-CY'),
                                                     ('Europe/Prague', 'cs'),
                                                     ('Europe/Berlin', 'de'),
                                                     ('Europe/Busingen', 'de'),
                                                     ('Africa/Djibouti', 'fr-DJ'),
                                                     ('Europe/Copenhagen', 'da-DK'),
                                                     ('America/Dominica', 'en-DM'),
                                                     ('America/Santo_Domingo', 'es-DO'),
                                                     ('Africa/Algiers', 'ar-DZ'),
                                                     ('America/Guayaquil', 'es-EC'),
                                                     ('Pacific/Galapagos', 'es-EC'),
                                                     ('Europe/Tallinn', 'et'),
                                                     ('Africa/Cairo', 'ar-EG'),
                                                     ('Africa/El_Aaiun', 'ar'),
                                                     ('Africa/Asmara', 'aa-ER'),
                                                     ('Europe/Madrid', 'es-ES'),
                                                     ('Africa/Ceuta', 'es-ES'),
                                                     ('Atlantic/Canary', 'es-ES'),
                                                     ('Africa/Addis_Ababa', 'am'),
                                                     ('Europe/Helsinki', 'fi-FI'),
                                                     ('Pacific/Fiji', 'en-FJ'),
                                                     ('Atlantic/Stanley', 'en-FK'),
                                                     ('Pacific/Chuuk', 'en-FM'),
                                                     ('Pacific/Pohnpei', 'en-FM'),
                                                     ('Pacific/Kosrae', 'en-FM'),
                                                     ('Atlantic/Faroe', 'fo'),
                                                     ('Europe/Paris', 'fr-FR'),
                                                     ('Africa/Libreville', 'fr-GA'),
                                                     ('Europe/London', 'en-GB'),
                                                     ('America/Grenada', 'en-GD'),
                                                     ('Asia/Tbilisi', 'ka'),
                                                     ('America/Cayenne', 'fr-GF'),
                                                     ('Europe/Guernsey', 'en'),
                                                     ('Africa/Accra', 'en-GH'),
                                                     ('Europe/Gibraltar', 'en-GI'),
                                                     ('America/Nuuk', 'kl'),
                                                     ('America/Danmarkshavn', 'kl'),
                                                     ('America/Scoresbysund', 'kl'),
                                                     ('America/Thule', 'kl'),
                                                     ('Africa/Banjul', 'en-GM'),
                                                     ('Africa/Conakry', 'fr-GN'),
                                                     ('America/Guadeloupe', 'fr-GP'),
                                                     ('Africa/Malabo', 'es-GQ'),
                                                     ('Europe/Athens', 'el-GR'),
                                                     ('Atlantic/South_Georgia', 'en'),
                                                     ('America/Guatemala', 'es-GT'),
                                                     ('Pacific/Guam', 'en-GU'),
                                                     ('Africa/Bissau', 'pt-GW'),
                                                     ('America/Guyana', 'en-GY'),
                                                     ('Asia/Hong_Kong', 'zh-HK'),
                                                     ('America/Tegucigalpa', 'es-HN'),
                                                     ('Europe/Zagreb', 'hr-HR'),
                                                     ('America/Port-au-Prince', 'ht'),
                                                     ('Europe/Budapest', 'hu-HU'),
                                                     ('Asia/Jakarta', 'id'),
                                                     ('Asia/Pontianak', 'id'),
                                                     ('Asia/Makassar', 'id'),
                                                     ('Asia/Jayapura', 'id'),
                                                     ('Europe/Dublin', 'en-IE'),
                                                     ('Asia/Jerusalem', 'he'),
                                                     ('Europe/Isle_of_Man', 'en'),
                                                     ('Asia/Kolkata', 'en-IN'),
                                                     ('Indian/Chagos', 'en-IO'),
                                                     ('Asia/Baghdad', 'ar-IQ'),
                                                     ('Asia/Tehran', 'fa-IR'),
                                                     ('Atlantic/Reykjavik', 'is'),
                                                     ('Europe/Rome', 'it-IT'),
                                                     ('Europe/Jersey', 'en'),
                                                     ('America/Jamaica', 'en-JM'),
                                                     ('Asia/Amman', 'ar-JO'),
                                                     ('Asia/Tokyo', 'ja'),
                                                     ('Africa/Nairobi', 'en-KE'),
                                                     ('Asia/Bishkek', 'ky'),
                                                     ('Asia/Phnom_Penh', 'km'),
                                                     ('Pacific/Tarawa', 'en-KI'),
                                                     ('Pacific/Enderbury', 'en-KI'),
                                                     ('Pacific/Kiritimati', 'en-KI'),
                                                     ('Indian/Comoro', 'ar'),
                                                     ('America/St_Kitts', 'en-KN'),
                                                     ('Asia/Pyongyang', 'ko-KP'),
                                                     ('Asia/Seoul', 'ko-KR'),
                                                     ('Asia/Kuwait', 'ar-KW'),
                                                     ('America/Cayman', 'en-KY'),
                                                     ('Asia/Almaty', 'kk'),
                                                     ('Asia/Qyzylorda', 'kk'),
                                                     ('Asia/Qostanay', 'kk'),
                                                     ('Asia/Aqtobe', 'kk'),
                                                     ('Asia/Aqtau', 'kk'),
                                                     ('Asia/Atyrau', 'kk'),
                                                     ('Asia/Oral', 'kk'),
                                                     ('Asia/Vientiane', 'lo'),
                                                     ('Asia/Beirut', 'ar-LB'),
                                                     ('America/St_Lucia', 'en-LC'),
                                                     ('Europe/Vaduz', 'de-LI'),
                                                     ('Asia/Colombo', 'si'),
                                                     ('Africa/Monrovia', 'en-LR'),
                                                     ('Africa/Maseru', 'en-LS'),
                                                     ('Europe/Vilnius', 'lt'),
                                                     ('Europe/Luxembourg', 'lb'),
                                                     ('Europe/Riga', 'lv'),
                                                     ('Africa/Tripoli', 'ar-LY'),
                                                     ('Africa/Casablanca', 'ar-MA'),
                                                     ('Europe/Monaco', 'fr-MC'),
                                                     ('Europe/Chisinau', 'ro'),
                                                     ('Europe/Podgorica', 'sr'),
                                                     ('America/Marigot', 'fr'),
                                                     ('Indian/Antananarivo', 'fr-MG'),
                                                     ('Pacific/Majuro', 'mh'),
                                                     ('Pacific/Kwajalein', 'mh'),
                                                     ('Europe/Skopje', 'mk'),
                                                     ('Africa/Bamako', 'fr-ML'),
                                                     ('Asia/Yangon', 'my'),
                                                     ('Asia/Ulaanbaatar', 'mn'),
                                                     ('Asia/Hovd', 'mn'),
                                                     ('Asia/Choibalsan', 'mn'),
                                                     ('Asia/Macau', 'zh'),
                                                     ('Pacific/Saipan', 'fil'),
                                                     ('America/Martinique', 'fr-MQ'),
                                                     ('Africa/Nouakchott', 'ar-MR'),
                                                     ('America/Montserrat', 'en-MS'),
                                                     ('Europe/Malta', 'mt'),
                                                     ('Indian/Mauritius', 'en-MU'),
                                                     ('Indian/Maldives', 'dv'),
                                                     ('Africa/Blantyre', 'ny'),
                                                     ('America/Mexico_City', 'es-MX'),
                                                     ('America/Cancun', 'es-MX'),
                                                     ('America/Merida', 'es-MX'),
                                                     ('America/Monterrey', 'es-MX'),
                                                     ('America/Matamoros', 'es-MX'),
                                                     ('America/Mazatlan', 'es-MX'),
                                                     ('America/Chihuahua', 'es-MX'),
                                                     ('America/Ojinaga', 'es-MX'),
                                                     ('America/Hermosillo', 'es-MX'),
                                                     ('America/Tijuana', 'es-MX'),
                                                     ('America/Bahia_Banderas', 'es-MX'),
                                                     ('Asia/Kuala_Lumpur', 'ms-MY'),
                                                     ('Asia/Kuching', 'ms-MY'),
                                                     ('Africa/Maputo', 'pt-MZ'),
                                                     ('Africa/Windhoek', 'en-NA'),
                                                     ('Pacific/Noumea', 'fr-NC'),
                                                     ('Africa/Niamey', 'fr-NE'),
                                                     ('Pacific/Norfolk', 'en-NF'),
                                                     ('Africa/Lagos', 'en-NG'),
                                                     ('America/Managua', 'es-NI'),
                                                     ('Europe/Amsterdam', 'nl-NL'),
                                                     ('Europe/Oslo', 'no'),
                                                     ('Asia/Kathmandu', 'ne'),
                                                     ('Pacific/Nauru', 'na'),
                                                     ('Pacific/Niue', 'niu'),
                                                     ('Pacific/Auckland', 'en-NZ'),
                                                     ('Pacific/Chatham', 'en-NZ'),
                                                     ('Asia/Muscat', 'ar-OM'),
                                                     ('America/Panama', 'es-PA'),
                                                     ('America/Lima', 'es-PE'),
                                                     ('Pacific/Tahiti', 'fr-PF'),
                                                     ('Pacific/Marquesas', 'fr-PF'),
                                                     ('Pacific/Gambier', 'fr-PF'),
                                                     ('Pacific/Port_Moresby', 'en-PG'),
                                                     ('Pacific/Bougainville', 'en-PG'),
                                                     ('Asia/Manila', 'tl'),
                                                     ('Asia/Karachi', 'ur-PK'),
                                                     ('Europe/Warsaw', 'pl'),
                                                     ('America/Miquelon', 'fr-PM'),
                                                     ('Pacific/Pitcairn', 'en-PN'),
                                                     ('America/Puerto_Rico', 'en-PR'),
                                                     ('Asia/Gaza', 'ar-PS'),
                                                     ('Asia/Hebron', 'ar-PS'),
                                                     ('Europe/Lisbon', 'pt-PT'),
                                                     ('Atlantic/Madeira', 'pt-PT'),
                                                     ('Atlantic/Azores', 'pt-PT'),
                                                     ('Pacific/Palau', 'pau'),
                                                     ('America/Asuncion', 'es-PY'),
                                                     ('Asia/Qatar', 'ar-QA'),
                                                     ('Indian/Reunion', 'fr-RE'),
                                                     ('Europe/Bucharest', 'ro'),
                                                     ('Europe/Belgrade', 'sr'),
                                                     ('Europe/Kaliningrad', 'ru'),
                                                     ('Europe/Moscow', 'ru'),
                                                     ('Europe/Kirov', 'ru'),
                                                     ('Europe/Astrakhan', 'ru'),
                                                     ('Europe/Volgograd', 'ru'),
                                                     ('Europe/Saratov', 'ru'),
                                                     ('Europe/Ulyanovsk', 'ru'),
                                                     ('Europe/Samara', 'ru'),
                                                     ('Asia/Yekaterinburg', 'ru'),
                                                     ('Asia/Omsk', 'ru'),
                                                     ('Asia/Novosibirsk', 'ru'),
                                                     ('Asia/Barnaul', 'ru'),
                                                     ('Asia/Tomsk', 'ru'),
                                                     ('Asia/Novokuznetsk', 'ru'),
                                                     ('Asia/Krasnoyarsk', 'ru'),
                                                     ('Asia/Irkutsk', 'ru'),
                                                     ('Asia/Chita', 'ru'),
                                                     ('Asia/Yakutsk', 'ru'),
                                                     ('Asia/Khandyga', 'ru'),
                                                     ('Asia/Vladivostok', 'ru'),
                                                     ('Asia/Ust-Nera', 'ru'),
                                                     ('Asia/Magadan', 'ru'),
                                                     ('Asia/Sakhalin', 'ru'),
                                                     ('Asia/Srednekolymsk', 'ru'),
                                                     ('Asia/Kamchatka', 'ru'),
                                                     ('Asia/Anadyr', 'ru'),
                                                     ('Europe/Simferopol', 'uk'),
                                                     ('Europe/Kiev', 'uk'),
                                                     ('Europe/Uzhgorod', 'uk'),
                                                     ('Europe/Zaporozhye', 'uk'),
                                                     ('Africa/Kigali', 'rw'),
                                                     ('Asia/Riyadh', 'ar-SA'),
                                                     ('Pacific/Guadalcanal', 'en-SB'),
                                                     ('Indian/Mahe', 'en-SC'),
                                                     ('Africa/Khartoum', 'ar-SD'),
                                                     ('Europe/Stockholm', 'sv-SE'),
                                                     ('Asia/Singapore', 'cmn'),
                                                     ('Atlantic/St_Helena', 'en-SH'),
                                                     ('Europe/Ljubljana', 'sl'),
                                                     ('Arctic/Longyearbyen', 'no'),
                                                     ('Europe/Bratislava', 'sk'),
                                                     ('Africa/Freetown', 'en-SL'),
                                                     ('Europe/San_Marino', 'it-SM'),
                                                     ('Africa/Dakar', 'fr-SN'),
                                                     ('Africa/Mogadishu', 'so-SO'),
                                                     ('America/Paramaribo', 'nl-SR'),
                                                     ('Africa/Juba', 'en'),
                                                     ('Africa/Sao_Tome', 'pt-ST'),
                                                     ('America/El_Salvador', 'es-SV'),
                                                     ('America/Lower_Princes', 'nl'),
                                                     ('Asia/Damascus', 'ar-SY'),
                                                     ('Africa/Mbabane', 'en-SZ'),
                                                     ('America/Grand_Turk', 'en-TC'),
                                                     ('Africa/Ndjamena', 'fr-TD'),
                                                     ('Indian/Kerguelen', 'fr'),
                                                     ('Africa/Lome', 'fr-TG'),
                                                     ('Asia/Bangkok', 'th'),
                                                     ('Asia/Dushanbe', 'tg'),
                                                     ('Pacific/Fakaofo', 'tkl'),
                                                     ('Asia/Dili', 'tet'),
                                                     ('Asia/Ashgabat', 'tk'),
                                                     ('Africa/Tunis', 'ar-TN'),
                                                     ('Pacific/Tongatapu', 'to'),
                                                     ('Europe/Istanbul', 'tr-TR'),
                                                     ('America/Port_of_Spain', 'en-TT'),
                                                     ('Pacific/Funafuti', 'tvl'),
                                                     ('Asia/Taipei', 'zh-TW'),
                                                     ('Africa/Dar_es_Salaam', 'sw-TZ'),
                                                     ('Africa/Kampala', 'en-UG'),
                                                     ('Pacific/Midway', 'en-UM'),
                                                     ('Pacific/Wake', 'en-UM'),
                                                     ('America/New_York', 'en-US'),
                                                     ('America/Detroit', 'en-US'),
                                                     ('America/Kentucky/Louisville', 'en-US'),
                                                     ('America/Kentucky/Monticello', 'en-US'),
                                                     ('America/Indiana/Indianapolis', 'en-US'),
                                                     ('America/Indiana/Vincennes', 'en-US'),
                                                     ('America/Indiana/Winamac', 'en-US'),
                                                     ('America/Indiana/Marengo', 'en-US'),
                                                     ('America/Indiana/Petersburg', 'en-US'),
                                                     ('America/Indiana/Vevay', 'en-US'),
                                                     ('America/Chicago', 'en-US'),
                                                     ('America/Indiana/Tell_City', 'en-US'),
                                                     ('America/Indiana/Knox', 'en-US'),
                                                     ('America/Menominee', 'en-US'),
                                                     ('America/North_Dakota/Center', 'en-US'),
                                                     ('America/North_Dakota/New_Salem', 'en-US'),
                                                     ('America/North_Dakota/Beulah', 'en-US'),
                                                     ('America/Denver', 'en-US'),
                                                     ('America/Boise', 'en-US'),
                                                     ('America/Phoenix', 'en-US'),
                                                     ('America/Los_Angeles', 'en-US'),
                                                     ('America/Anchorage', 'en-US'),
                                                     ('America/Juneau', 'en-US'),
                                                     ('America/Sitka', 'en-US'),
                                                     ('America/Metlakatla', 'en-US'),
                                                     ('America/Yakutat', 'en-US'),
                                                     ('America/Nome', 'en-US'),
                                                     ('America/Adak', 'en-US'),
                                                     ('Pacific/Honolulu', 'en-US'),
                                                     ('America/Montevideo', 'es-UY'),
                                                     ('Asia/Samarkand', 'uz'),
                                                     ('Asia/Tashkent', 'uz'),
                                                     ('Europe/Vatican', 'la'),
                                                     ('America/St_Vincent', 'en-VC'),
                                                     ('America/Caracas', 'es-VE'),
                                                     ('America/Tortola', 'en-VG'),
                                                     ('America/St_Thomas', 'en-VI'),
                                                     ('Asia/Ho_Chi_Minh', 'vi'),
                                                     ('Pacific/Efate', 'bi'),
                                                     ('Pacific/Wallis', 'wls'),
                                                     ('Pacific/Apia', 'sm'),
                                                     ('Asia/Aden', 'ar-YE'),
                                                     ('Indian/Mayotte', 'fr-YT'),
                                                     ('Africa/Johannesburg', 'zu'),
                                                     ('Africa/Lusaka', 'en-ZM'),
                                                     ('Africa/Harare', 'en-ZW') ON CONFLICT DO NOTHING;

INSERT INTO public.languages(shortname, name) VALUES ('af', 'Afrikaans'),
                                                     ('ar', 'Arabic'),
                                                     ('ca', 'Catalan'),
                                                     ('cs', 'Czech'),
                                                     ('da', 'Danish'),
                                                     ('de', 'German'),
                                                     ('el', 'Greek'),
                                                     ('en-US', 'English'),
                                                     ('es-ES', 'Spanish'),
                                                     ('fi', 'Finnish'),
                                                     ('fr', 'French'),
                                                     ('he', 'Hebrew'),
                                                     ('hi', 'Hindi'),
                                                     ('hu', 'Hungarian'),
                                                     ('id', 'Indonesian'),
                                                     ('it', 'Italian'),
                                                     ('ja', 'Japanese'),
                                                     ('ko', 'Korean'),
                                                     ('ms', 'Malay'),
                                                     ('nl', 'Dutch'),
                                                     ('no', 'Norwegian'),
                                                     ('pl', 'Polish'),
                                                     ('pt-BR', 'Portuguese (Brazil)'),
                                                     ('pt-PT', 'Portuguese (Portugal)'),
                                                     ('ro', 'Romanian'),
                                                     ('ru', 'Russian'),
                                                     ('so', 'Somali'),
                                                     ('sr', 'Serbian'),
                                                     ('sv-SE', 'Swedish'),
                                                     ('tl', 'Tagalog'),
                                                     ('tr', 'Turkish'),
                                                     ('uk', 'Ukrainian'),
                                                     ('ur-PK', 'Urdu'),
                                                     ('vi', 'Vietnamese'),
                                                     ('zh-CN', 'Chinese') ON CONFLICT DO NOTHING;

INSERT INTO public.apiaccess(accessid, name) VALUES (-1, 'God'), (0, 'Owner'), (1, 'Developer'), (2, 'Super Patron'), (3, 'Friend'), (4, 'User') ON CONFLICT DO NOTHING;

INSERT INTO modes(modeid, name) VALUES(1, 'Normal'), (2, 'Group') ON CONFLICT DO NOTHING;
INSERT INTO difficulty(difficultyid, name) VALUES(1, 'easy'), (2, 'medium'), (3, 'hard') ON CONFLICT DO NOTHING;


INSERT INTO public.eightball(responseid, response) VALUES
      (1, 'It is certain.'),
      (2, 'It is decidedly so.'),
      (3, 'Without a doubt.'),
      (4, 'Yes - definitely.'),
      (5, 'You may rely on it.'),
      (6, 'As I see it, yes.'),
      (7, 'Most likely.'),
      (8, 'Outlook good.'),
      (9, 'Yes.'),
      (10, 'Signs point to yes.'),
      (11, ':thumbsup:'),
      (12, 'Well, duh'),
      (13, 'Of course, that was a stupid question.'),
      (14, 'Reply hazy, try again.'),
      (15, 'Ask again later.'),
      (16, 'Better not tell you now.'),
      (17, 'Cannot predict now.'),
      (18, 'Concentrate and ask again.'),
      (19, 'Why the fuck are you asking me you dumb rat.'),
      (20, 'You should already know this you 바보.'),
      (21, 'Do not count on it.'),
      (22, 'My reply is no.'),
      (23, 'My sources say no.'),
      (24, 'Outlook not so good.'),
      (25, 'Very doubtful.'),
      (26, ':thumbsdown:'),
      (27, 'Are you kidding?'),
      (28, 'Do not bet on it.'),
      (29, 'Forget about it.'),
      (30, 'It is just not meant to be.') ON CONFLICT DO NOTHING;


INSERT INTO public.languagepacks(languageid, label, message) VALUES
(8,'error_limit_rounds','Your max rounds must be in between :1$MIN ROUNDS$1: and :2$MAX ROUNDS$2:'),
(8,'error_difficulty_options','Your difficulty must be one of the options: :1$OPTIONS$1:'),
(8,'error_gender_options','Your gender choice needs to be one of the options: :1$OPTIONS$1:'),
(8,'error_timeout_options','Your timeout must be in between :1$MIN TIMEOUT$1: and :2$MAX TIMEOUT$2: seconds.'),
(8,'error_invalid_input','Your input does not work.'),
(8,'start_us','Starting Unscramble Game with `:1$MAX ROUNDS$1:`, a timeout of `:2$TIMEOUT$2:` seconds per round, a difficulty of `:3$DIFFICULTY$3:`, and with the gender selected as `:4$GENDER$4:`.'),
(8,'error_nsfw_options','Your NSFW choice must be `:1$CHOICE$1:` or `:2$CHOICE$2:`.'),
(8,'start_gg','Starting :1$GAME TYPE$1:Guessing Game with `:2$ROUNDS$2:` rounds, a timeout of `:3$TIMEOUT$3:` seconds per round, a difficulty of `:4$DIFFICULTY$4:`, with the gender selected as `:5$GENDER$5:`, and `:6$NSFW SELECTION$6:` contain NSFW content.'),
(8,'toggle_gg_filter','Your guessing game filter (including groups) is now :1$STATUS$1:.'),
(8,'error_gg_filter_selection','No :1$OBJECT TYPE$1: exists with that ID.'),
(8,'view_gg_filter','Your GG Filter for :1$OBJECT TYPE$1: is now: :2$LIST ITEMS$2:'),
(8,'error_twitter_username','That username does not exist on Twitter.'),
(8,'twitter_subscribed',':1$CHANNEL$1: is now subscribed to :2$USERNAME$2: on Twitter.'),
(8,'twitter_list','These are the Twitter subscriptions in :1$GUILD$1: :2$SUBSCRIPTIONS$2:'),
(8,'twitter_unsubscribed',':1$CHANNEL$1: is no longer subscribed to :2$USERNAME$2:.'),
(8,'twitch_list','These are the Twitch subscriptions in :1$GUILD$1: :2$SUBSCRIPTIONS$2:'),
(8,'error_twitch_username','That username does not exist on Twitch.'),
(8,'twitch_subscribed',':1$CHANNEL$1: is now subscribed to :2$USERNAME$2: on Twitch.'),
(8,'twitch_unsubscribed',':1$CHANNEL$1: is no longer subscribed to :2$USERNAME$2:.'),
(8,'error_division_by_zero','It is not possible to divide by zero.'),
(8,'error_wolfram_patron','In order to use this feature, you must be a supporter/patron of the bot.'),
(8,'wolfram_query','**Input:** :1$QUERY$1:\n**Result:** :2$QUERY$2:'),
(8,'wolfram_no_results','WolframAlpha did not return a result for that query.'),
(8,'biasgame_not_enough','There are not enough players to fill this BiasGame.'),
(8,'error_bracket_size','Your bracket size must be one of the following numbers: :1$OPTIONS$1:.'),
(8,'start_bg','Starting BiasGame with a bracket size of `:1$BRACKET SIZE$1:` and with the gender selected as `:2$GENDER$2:`.'),
(8,'list_bg','BiasGame Results for <@:1$USER ID$1:>:\n :2$RESULTS$2:'),
(8,'stop_games','Stopping all games that you host.'),
(8,'already_in_game','You are already in a game. Use the command `stopgames` to force-quit all your games.'),
(8,'correct_answer_gg','The correct answer was :1$STAGE NAME$1: from :2$GROUP NAME$2:'),
(8,'incorrect_answer_gg','No one guessed correctly.'),
(8,'winner_gg_msg',':1$USERNAME$1: won the round.'),
(8,'all_answers_gg','Possible answers: :1$CORRECT ANSWERS$1:'),
(8,'correct_answer_ggg','The correct answer was :1$GROUP NAME$1:'),
(8,'final_scores_games','The final scores are:\n\n:1$SCORES$1:'),
(8,'game_finished_no_scores','The Game has finished! No one has received a point in the Game.'),
(8,'become_a_patron_limited','Further usage of this function requires patron status from https://www.patreon.com/mujykun'),
(8,'us_question','The name I want you to unscramble is :1$QUESTION$1:'),
(8,'no_results','There are no results for that selection.'),
(8,'choose_options','**Possible Choices**: :1$CHOICES$1:\n**Selection**: :2$SELECTION$2:'),
(8,'8ball_add_response','`:1$RESPONSE$1:` has been added as an 8ball response.'),
(8,'8ball_delete_response','`:1$RESPONSE ID$1:` has been deleted as an 8ball response.'),
(8,'8ball_list_response','Here is a list of 8ball responses:\n`:1$RESPONSES$1:`'),
(8,'media_not_found','`:1$MEDIA ID$1:` could not be found as a media id.'),
(8,'media_who_is','`:1$MEDIA ID$1:` belongs to :2$RESULT$2:.'),
(8, 'noti_already_exists', 'That phrase already exists as one of your notification phrases.'),
(8, 'noti_does_not_exist', 'That phrase does not exist as one of your notification phrases.'),
(8, 'noti_added', 'That phrase is now one of your notification phrases.'),
(8, 'noti_removed', 'That phrase has been removed from your notification phrases if it existed.'),
(8, 'noti_list', 'This is a list of your notification phrases in this server:\n:1$PHRASES$1: '),
(8, 'noti_list', 'This is a list of your notification phrases in this server:\n:1$PHRASES$1: '),
(8, 'noti_list', 'This is a list of your notification phrases in this server:\n:1$PHRASES$1: '),
(8, 'interaction_type_exists', 'That interaction type already exists.'),
(8, 'interaction_type_does_not_exist', 'That interaction type does not exist.'),
(8, 'interaction_type_added', 'That interaction type has been added.'),
(8, 'interaction_type_deleted', 'That interaction type has been deleted.'),
(8, 'interaction_added', 'That interaction has been added.'),
(8, 'interaction_does_not_exist', 'That interaction does not exist.'),
(8, 'interaction_already_exists', 'That interaction already exists'),
(8, 'interaction_deleted', 'That interaction has been deleted.'),
(8, 'interaction_no_results', 'No results exist for that interaction.'),
(8, 'no_self_harm', ':1$BOT NAME$1: does not support self harm.'),
(8, 'ping', 'My ping is currently :1$LATENCY$1:ms'),
(8, 'messages_cleared', 'Cleared :1$NUMBER OF MESSAGES$1: messages.'),
(8, 'not_in_range', 'The amount must be in a range from :1$MIN$1: to :2$MAX$2:'),
(8, 'no_banner', 'There is no banner found.'),
(8, 'nice_try_cheater', 'Nice Try Cheater! You are currently in a game!'),
(8, 'no_emojis_found', 'No emojis were found.'),
(8, 'invalid_range', 'There was an invalid range specified. The start number may be higher than the end number.'),
(8, 'random_number', 'Your random number between :1$START NUMBER$1: and :2$END NUMBER$2: is: :3$RESULT$3:'),
(8, 'urban_result', 'Phrase: :1$PHRASE$1:\nDefinition Number: :2$DEFINITION NUMBER$2:\nDefinition: :3$DEFINITION$3:'),
(8, 'no_urban_result', 'That phrase and definition number did not provide any results.'),
(8,'8ball_response','**Question:** :1$PROMPT$1:\n**Answer:** :2$ANSWER$2:') ON CONFLICT DO NOTHING;


SELECT setval('public.eightball_responseid_seq', (SELECT MAX(responseid) FROM public.eightball)+1);
SELECT setval('public.apiaccess_accessid_seq', (SELECT MAX(accessid) FROM public.apiaccess)+1);
SELECT setval('public.modes_modeid_seq', (SELECT MAX(modeid) FROM public.modes)+1);
SELECT setval('public.difficulty_difficultyid_seq', (SELECT MAX(difficultyid) FROM public.difficulty)+1);
